### ISSUE TITLE
Is is able to use it for normal PCs with Nviida cards on Ubuntu?

### ISSUE THREAD

**Issue by jundengdeng** [jetsonhacks/gpuGraphTX#1]
Hi there,

First of all, thanks a lot for sharing it with the community. For me, I'd like to use it for normal PCs instead of  Jetson TX1 and TX2. I have tried to adapted it to my usage, but I haven't found a proper way to do it. Maybe,  do you happen to know how to do it? 

Thanks again for your help!

Best,

Jun

**Comment by jetsonhacks** [comment]
You're welcome for the code share. This code uses tegrastats to read the GPU usage. The tegrastats utility is specific to the Tegra chips (Jetsons in this case), and therefore will not run on the desktop GPUs.
